language: node_js
node_js:
  - "v9.11.2"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: gae
  project: "vesselbuilder-frontend"
on:
  branch: master
services:
  - docker
