

export const LOAD_AUTH_MODEL = 'LOAD_AUTH_MODEL';
export const IMPORT_AUTH_MODEL = 'IMPORT_AUTH_MODEL';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const IMPORT_MODEL = 'IMPORT_MODEL';
export const CLICK_MENU = 'CLICK_MENU';
export const DISABLE_NEW = 'DISABLE_NEW';
export const UPDATE_TITLE = 'UPDATE_TITLE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const LOAD_FORM_MODEL = 'LOAD_FORM_MODEL';
export const IMPORT_NEW_MODEL = 'IMPORT_NEW_MODEL';
export const IMPORT_OPEN_MODEL = 'IMPORT_OPEN_MODEL';
export const IMPORT_COMPONENT_MODEL = 'IMPORT_COMPONENT_MODEL';
export const IMPORT_FORM_MODEL = 'IMPORT_FORM_MODEL';
export const IMPORT_PROJECTS = 'IMPORT_PROJECTS';
export const IMPORT_SPECIFIC_PROJECT = 'IMPORT_SPECIFIC_PROJECT';
export const IMPORT_SPECIFIC_PROJECT_SAGA = 'IMPORT_SPECIFIC_PROJECT_SAGA';
export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS';
export const ON_SUBMIT_AND_UPDATE = 'ON_SUBMIT_AND_UPDATE';
export const UPDATE_P_T_D = 'UPDATE_P_T_D';
export const COMPONENT_CLICKED = 'COMPONENT_CLICKED';
export const RETURN_COMPONENT_BY_ID = 'RETURN_COMPONENT_BY_ID';
export const OPEN_FORM_DIALOG = 'OPEN_FORM_DIALOG';

export const UPDATE_THICKNESS = 'UPDATE_THICKNESS';

export const DATA_SEND_FAIL = 'DATA_SEND_FAIL';

export const DATA_UPDATE = 'DATA_UPDATE';
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT';
export const DELETE_THICKNESS = 'DELETE_THICKNESS';
export const DELETE_LAST_COMPONENT = 'DELETE_LAST_COMPONENT';
export const DELETE_SPECIFIC_COMPONENT = 'DELETE_SPECIFIC_COMPONENT';
export const DELETE_SPECIFIC_COMPONENT_IN_SERVER = 'DELETE_SPECIFIC_COMPONENT_IN_SERVER'
export const SELECTED_COMPONENT_ID = 'SELECTED_COMPONENT_ID';

export const ID_UPDATE = 'ID_UPDATE';

export const SHOW_SPINNER = 'SHOW_SPINNER';


export const COMPONENT_UPDATE = 'COMPONENT_UPDATE';
export const LOAD_COMPONENT_TREE = 'LOAD_COMPONENT_TREE';

export const SEND_COMPONENT_ID = 'SEND_COMPONENT_ID';

export const LOAD_NEXT = 'LOAD_NEXT';
export const LOAD_PREVIOUS = 'LOAD_PREVIOUS';

export const UPDATE_NUM = 'UPDATE_NUM';

export const ON_PROJECT_ID_RECEIVED = "ON_PROJECT_ID_RECEIVED";
export const REQUEST_NEW_REPORT = "REQUEST_NEW_REPORT";
export const REPORT_FAIL = "REPORT_FAIL";

export const DOWNLOAD_REPORT = "DOWNLOAD_REPORT";

export const UPDATE_LAST_ITEM = 'UPDATE_LAST_ITEM';

export const CLEAR_COMPONENT_DATA = 'CLEAR_COMPONENT_DATA';
export const CLEAR_COMPONENT_ID = 'CLEAR_COMPONENT_ID';
export const SEND_COMPONENT = 'SEND_COMPONENT';

export const REQUEST_NEW_PROJECT = 'REQUEST_NEW_PROJECT';