export const CLICK_MENU = 'CLICK_MENU';

export const DISABLE_NEW = 'DISABLE_NEW';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const IMPORT_COMPONENT_MODEL = 'IMPORT_COMPONENT_MODEL';
export const IMPORT_FORM_MODEL = 'IMPORT_FORM_MODEL';
export const IMPORT_AUTH_MODEL = 'IMPORT_AUTH_MODEL';
export const IMPORT_PROJECTS = 'IMPORT_PROJECTS';
export const IMPORT_SPECIFIC_PROJECT = 'IMPORT_SPECIFIC_PROJECT';
export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS';
export const OPEN_FORM_DIALOG = 'OPEN_FORM_DIALOG';

export const DATA_SEND = 'DATA_SEND';

export const DATA_SEND_FAIL = 'DATA_SEND_FAIL';

export const DATA_UPDATE = 'DATA_UPDATE';
export const DATA_UPDATE1 = 'DATA_UPDATE1';
export const DELETE_THICKNESS = 'DELETE_THICKNESS';

export const ID_UPDATE = 'ID_UPDATE';

export const COMPONENT_UPDATE = 'COMPONENT_UPDATE';
export const LOAD_COMPONENT_TREE = 'LOAD_COMPONENT_TREE';

export const SEND_COMPONENT_ID = 'SEND_COMPONENT_ID';

export const LOAD_NEXT = 'LOAD_NEXT';
export const LOAD_PREVIOUS = 'LOAD_PREVIOUS';

export const UPDATE_NUM = 'UPDATE_NUM';

export const REQUEST_REPORT = "REQUEST_REPORT";
export const REPORT_FAIL = "REPORT_FAIL";

export const DOWNLOAD_REPORT = "DOWNLOAD_REPORT";

export const UPDATE_LAST_ITEM = 'UPDATE_LAST_ITEM';